Fixingbugs...
Need to look at this bug:

  File "C:\Users\Spectral\Anaconda3\envs\ASLM\lib\tkinter\__init__.py", line 1885, in __call__
    return self.func(*args)
  File "C:\Users\Spectral\Documents\GitHub\ASLM\src\controller\sub_controllers\acquire_bar_controller.py", line 100, in launch_popup_window
    self.parent_controller.execute('acquire')
  File "C:\Users\Spectral\Documents\GitHub\ASLM\src\controller\aslm_controller.py", line 279, in execute
    self.threads_pool.createThread('camera', self.model.acquire_image())
  File "C:\Users\Spectral\Documents\GitHub\ASLM\src\model\aslm_model.py", line 70, in acquire_image
    self.daq.write_waveforms_to_tasks()
  File "C:\Users\Spectral\Documents\GitHub\ASLM\src\model\devices\daq\NI\NIDAQ.py", line 331, in write_waveforms_to_tasks
    self.galvo_etl_task.write(self.galvo_and_etl_waveforms)
  File "C:\Users\Spectral\Anaconda3\envs\ASLM\lib\site-packages\nidaqmx\task.py", line 1221, in write
    self._raise_invalid_write_num_chans_error(
  File "C:\Users\Spectral\Anaconda3\envs\ASLM\lib\site-packages\nidaqmx\task.py", line 1092, in _raise_invalid_write_num_chans_error
    raise DaqError(
nidaqmx.errors.DaqError: Write cannot be performed, because the number of channels in the data does not match the number of channels in the task.

When writing, supply data for all channels in the task. Alternatively, modify the task to contain the same number of channels as the data written.

Number of Channels in Task: 4
Number of Channels in Data: 1