Apple & TensorFlow
Sorry to introducing the module loading error for Apple devices.  Should be fixed now. #74...

Did get this error though on exit.
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\AI2\Anaconda3\envs\ASLM\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "C:\Users\AI2\Documents\GitHub\ASLM\src\controller\sub_controllers\acquire_bar_controller.py", line 188, in exit_program
    self.parent_controller.execute('exit')
  File "C:\Users\AI2\Documents\GitHub\ASLM\src\controller\aslm_controller.py", line 540, in execute
    self.model.run_command('stop')
  File "C:\Users\AI2\Documents\GitHub\ASLM\src\model\concurrency\concurrency_tools.py", line 376, in attr
    return _get_response(self, True)
  File "C:\Users\AI2\Documents\GitHub\ASLM\src\model\concurrency\concurrency_tools.py", line 396, in _get_response
    raise resp
AttributeError: 'NoneType' object has no attribute 'join'