Tiling wizard now populates multi position table (#145)
* Squashed commit of the following:

commit 00570e34dba8679667ed2b232b61c546d00aa695
Author: Kevin Dean <42547789+AdvancedImagingUTSW@users.noreply.github.com>
Date:   Tue Jul 12 09:59:48 2022 -0500

    Slight spacing tweak

    Co-Authored-By: Zach Marin <zacsimile@users.noreply.github.com>

commit 03bd5897538d1d9efb661a33fac397a91de52098
Author: Kevin Dean <42547789+AdvancedImagingUTSW@users.noreply.github.com>
Date:   Tue Jul 12 09:36:11 2022 -0500

    Remove mousewheel for now due to conflicts with camera_view_controller

    Co-Authored-By: Zach Marin <zacsimile@users.noreply.github.com>

commit 3559657e4f3638581f23f94b465d8f4efaa8d0e2
Author: Kevin Dean <42547789+AdvancedImagingUTSW@users.noreply.github.com>
Date:   Tue Jul 12 09:29:22 2022 -0500

    Tweaks

    Co-Authored-By: Zach Marin <zacsimile@users.noreply.github.com>

commit 637d5913c974d08b089d6d07d633e7e2c5dd8b33
Author: Kevin Dean <42547789+AdvancedImagingUTSW@users.noreply.github.com>
Date:   Tue Jul 12 09:14:38 2022 -0500

    Make @Rapuris wsad code work

    Co-Authored-By: Zach Marin <zacsimile@users.noreply.github.com>

commit b8c8e0297ced4c441cc886ea306e0006945f0ed1
Author: Dax Collison <79557266+codeCollision4@users.noreply.github.com>
Date:   Mon Jul 11 16:31:55 2022 -0500

    Chaos averted

commit 1d2a9a3b50e3e69d099f2060839cb9ac7a94af26
Merge: 9a3ced2 83cba7c
Author: Dax Collison <79557266+codeCollision4@users.noreply.github.com>
Date:   Mon Jul 11 15:35:53 2022 -0500

    Resolving conflicts from Chaos

commit 9a3ced2b392371581257a143956893c1f42c9b08
Author: Dax Collison <79557266+codeCollision4@users.noreply.github.com>
Date:   Mon Jul 11 15:22:57 2022 -0500

    Redoing PR#142 Laser Settings

commit 83cba7c59751a970827f475c9a31d98724db7860
Merge: 8cf7520 7c260f7
Author: Rapuris <91913098+Rapuris@users.noreply.github.com>
Date:   Mon Jul 11 16:13:27 2022 -0400

    Merge branch 'develop' of https://github.com/AdvancedImagingUTSW/ASLM into develop

commit 7c260f72f9b9944e5977afecbdc141934eca4a3c
Author: Dax Collison <79557266+codeCollision4@users.noreply.github.com>
Date:   Mon Jul 11 13:58:22 2022 -0500

    Revert "Chaos"

    This reverts commit ca317bb2b8a4df2fff7dbdddd68c432e2dd1660f.

commit dccb021d956d77e66aefd5cc22a5f1569b09d56b
Author: Dax Collison <79557266+codeCollision4@users.noreply.github.com>
Date:   Mon Jul 11 13:52:27 2022 -0500

    Fixing stage control

commit 48b8c0adba0c0d00dc363abff40b6239b8114c23
Author: Dax Collison <79557266+codeCollision4@users.noreply.github.com>
Date:   Mon Jul 11 13:46:32 2022 -0500

    Fixing acquire bar

commit ca317bb2b8a4df2fff7dbdddd68c432e2dd1660f
Author: Rapuris <91913098+Rapuris@users.noreply.github.com>
Date:   Mon Jul 11 14:15:54 2022 -0400

    Chaos

    * working on redesigning stage control

    * added wasd + mousewheel

    * Prototype New Stage Movement GUI

    * Update aslm_controller.py

    * change mousewheel to f

    * fixing mousewheel

    * finished separating

    * removing for base branch

    Finished adding all changes (#142)

    Greyed out timepoints settings (#135)

    * working on redesigning stage control

    * added wasd + mousewheel

    * Prototype New Stage Movement GUI

    * Update aslm_controller.py

    * change mousewheel to f

    * fixing mousewheel

    * finished separating

    * get rid of mousewheel stuff

    create base branch to add other gui features/styling

    * grayed out timepoint settings

    * merge with develop

    Greyed out stack acq settings (#136)

    * working on redesigning stage control

    * added wasd + mousewheel

    * Prototype New Stage Movement GUI

    * Update aslm_controller.py

    * change mousewheel to f

    * fixing mousewheel

    * finished separating

    * get rid of mousewheel stuff

    create base branch to add other gui features/styling

    * greyed out stack acq settings

    * Updating xy

    Revert "Greyed out stack acq settings (#136)"

    This reverts commit 31d642264b515adf12226224830f0eb8e74f3aa0.

    Revert "Revert "Greyed out stack acq settings (#136)""

    This reverts commit fec4bfc684d2cfc74a45cd07775efc76785d93a2.

    Fix

    Update acquire_bar_controller.py

    Update acquire_bar_controller.py

    Revert "WASD/Mousewheel (#134)"

    This reverts commit b8ac2e680c9e616d52f47ea7c0ab6ea14f4a64cd.

    Revert "Finished adding all changes (#142)"

    This reverts commit 8cf75206f5fda2d6782ed15010b0322f5a2d9c97.

    Update acquire_bar_controller.py

    Fix

    Update acquire_bar_controller.py

    Revert "Fix"

    This reverts commit d4ac45dcacbd0677f347569ce5e517ca692c3440.

    Co-Authored-By: Dax Collison <collisod@gmail.com>
    Co-Authored-By: Dax Collison <79557266+codeCollision4@users.noreply.github.com>

commit 8cf75206f5fda2d6782ed15010b0322f5a2d9c97
Author: Rapuris <91913098+Rapuris@users.noreply.github.com>
Date:   Mon Jul 11 14:19:09 2022 -0400

    Finished adding all changes (#142)

commit b8ac2e680c9e616d52f47ea7c0ab6ea14f4a64cd
Author: Rapuris <91913098+Rapuris@users.noreply.github.com>
Date:   Mon Jul 11 14:15:54 2022 -0400

    WASD/Mousewheel (#134)

    * working on redesigning stage control

    * added wasd + mousewheel

    * Prototype New Stage Movement GUI

    #107 finished the prototype of a new GUI that should work in minimized or maximized screen

    * Update aslm_controller.py

    * change mousewheel to f

    * fixing mousewheel

    * finished separating

    * removing for base branch

    Co-authored-by: Dax Collison <collisod@gmail.com>

commit 6c5147bf510d17d6789b0dc49fd5a0511aa4eb8d
Author: Kevin Dean <42547789+AdvancedImagingUTSW@users.noreply.github.com>
Date:   Mon Jul 11 09:55:18 2022 -0500

    KCube updates

    Co-Authored-By: Zach Marin <zacsimile@users.noreply.github.com>

commit 4bd42bd6b3e369b5c24e427565be4522ac10171d
Author: Kevin Dean <42547789+AdvancedImagingUTSW@users.noreply.github.com>
Date:   Mon Jul 11 08:36:06 2022 -0500

    Fixes for new display

    Co-Authored-By: Zach Marin <zacsimile@users.noreply.github.com>

commit 4a4c04b67a05c1e2fb0c062b2b318c01ca28434b
Author: Zach Marin <zacsimile@users.noreply.github.com>
Date:   Mon Jul 11 07:26:51 2022 -0500

    Cleanup, MoveJog and TLI_DeviceInfo (#141)

commit 031c922e64e97173c136aa81e9c9dac88777777c
Author: Microscopy Innovation Lab <42547789+AdvancedImagingUTSW@users.noreply.github.com>
Date:   Sun Jul 10 13:35:45 2022 -0500

    The start of more view functionality

    Beginning to implement having MIPs displayed instead of live images, and a slider wheel to go through the individual frames as they are acquired.

commit 31ed0cb652d18a6cc22a33267004e4579814ae3b
Author: Microscopy Innovation Lab <42547789+AdvancedImagingUTSW@users.noreply.github.com>
Date:   Sun Jul 10 06:24:49 2022 -0500

    Cleanup

    Getting a custody error.  I saw this yesterday on the Linux machine too.

    stage thread exception happened! Two different threads tried to use the same ObjectInSubprocess at the same time! This is bad. Look at the docstring of concurrency_tools.py to see an example of how to use a _Custody object to avoid this problem. Traceback (most recent call last):
      File "/Users/S155475/Desktop/GitHub/ASLM/src/aslm/controller/thread_pool.py", line 146, in func
        target(*args, **kwargs)
      File "/Users/S155475/Desktop/GitHub/ASLM/src/aslm/controller/aslm_controller.py", line 754, in move_stage
        success = self.model.move_stage(pos_dict)
      File "/Users/S155475/Desktop/GitHub/ASLM/src/aslm/model/concurrency/concurrency_tools.py", line 373, in __getattr__
        with self._.parent_pipe_lock:
      File "/Users/S155475/Desktop/GitHub/ASLM/src/aslm/model/concurrency/concurrency_tools.py", line 538, in __enter__
        raise RuntimeError(
    RuntimeError: Two different threads tried to use the same ObjectInSubprocess at the same time! This is bad. Look at the docstring of concurrency_tools.py to see an example of how to use a _Custody object to avoid this problem.

commit f6511e1515c7d700b4fac5e6b592772b00e1fe73
Merge: cb37ff4 5fc9b9b
Author: Microscopy Innovation Lab <42547789+AdvancedImagingUTSW@users.noreply.github.com>
Date:   Sun Jul 10 06:16:17 2022 -0500

    Merge branch 'develop' of https://github.com/AdvancedImagingUTSW/ASLM into develop

commit cb37ff4387e69e81e8401ebfcc75cb65977764da
Author: Microscopy Innovation Lab <42547789+AdvancedImagingUTSW@users.noreply.github.com>
Date:   Sun Jul 10 06:16:14 2022 -0500

    Progress bar and more.

    Not sure why this didn't push on Friday.  I've had some weird issues with my laptop. I did this on Friday, and it makes the progress bar more intelligent.  Also been slowly adding more image metrics.

commit 5fc9b9b05326a574bce401f9142206427fe83515
Author: Kevin Dean <42547789+AdvancedImagingUTSW@users.noreply.github.com>
Date:   Sat Jul 9 12:24:16 2022 -0500

    Cleanup

    Co-Authored-By: Zach Marin <zacsimile@users.noreply.github.com>

commit 861486f597c806bd9cf04d60f960c886fe4b4676
Author: AdvancedImagingUTSW <kevin.dean@utsouthwestern.edu>
Date:   Sat Jul 9 09:39:42 2022 -0500

    digital zoom and menu items on camera display.  Need to wire up the move stage command and account for the fact that it is relative to a 512x512 widget and not the image necessarily

commit 710b41d6093ec64306d5bc9a2a636d93208e6bb7
Author: Kevin Dean <42547789+AdvancedImagingUTSW@users.noreply.github.com>
Date:   Fri Jul 8 19:23:44 2022 -0500

    Better control of the focus stage

    Co-Authored-By: Zach Marin <zacsimile@users.noreply.github.com>

commit 4084b9bd09a72e52088e4fe1f19d7650fb5257ae
Author: Dax Collison <79557266+codeCollision4@users.noreply.github.com>
Date:   Fri Jul 8 17:54:27 2022 -0500

    Fixing Total Tiles #58

    This finishes base setup of tiling wizard

commit a2c7ef19b057082da7e0f4841f0201efa2ea3b78
Author: Kevin Dean <42547789+AdvancedImagingUTSW@users.noreply.github.com>
Date:   Fri Jul 8 17:48:11 2022 -0500

    Slight more synthetic hardware avoidance for stages_r

    Co-Authored-By: Zach Marin <zacsimile@users.noreply.github.com>

commit 733aa2f4d9c37fba692886eb8451729b24c288da
Merge: 14d4add f21428b
Author: Kevin Dean <42547789+AdvancedImagingUTSW@users.noreply.github.com>
Date:   Fri Jul 8 17:46:06 2022 -0500

    Merge branch 'develop' of https://github.com/AdvancedImagingUTSW/ASLM into develop

commit 14d4add0d80752bf4ee62e793f6ef4721a4a8d34
Author: Kevin Dean <42547789+AdvancedImagingUTSW@users.noreply.github.com>
Date:   Fri Jul 8 17:46:00 2022 -0500

    Don't load stages_r if synthetic

    Co-Authored-By: Zach Marin <zacsimile@users.noreply.github.com>

commit f21428b2a29edc6da4cd4ff524b83f5396bedb81
Author: Dax Collison <79557266+codeCollision4@users.noreply.github.com>
Date:   Fri Jul 8 17:30:13 2022 -0500

    Tiling Wizard base setup done #58

    Tiles now update when FOV, overlay and distance are changed. Step size mimics stack acq settings. Total tiles now update when other axis tile amounts change.

commit 7b8db0aff74223f71c82de1f693ebc239f725abf
Author: Kevin Dean <42547789+AdvancedImagingUTSW@users.noreply.github.com>
Date:   Fri Jul 8 16:55:00 2022 -0500

    Update using correct dictionary

    Co-Authored-By: Zach Marin <zacsimile@users.noreply.github.com>

commit 771b26fc202fcf33f3539eecf7c836e8716e7089
Author: Kevin Dean <42547789+AdvancedImagingUTSW@users.noreply.github.com>
Date:   Fri Jul 8 15:12:22 2022 -0500

    Stage reporting updates

    Co-Authored-By: Zach Marin <zacsimile@users.noreply.github.com>

commit 6d2bbddaba8a2a6e93a54893d118734f4422c4d2
Author: Kevin Dean <42547789+AdvancedImagingUTSW@users.noreply.github.com>
Date:   Fri Jul 8 14:05:52 2022 -0500

    Stage fixes

    Co-Authored-By: Zach Marin <zacsimile@users.noreply.github.com>

commit 576cb1cfa3a4848212dbb605fbc027ca416c6b94
Author: Kevin Dean <42547789+AdvancedImagingUTSW@users.noreply.github.com>
Date:   Fri Jul 8 13:18:26 2022 -0500

    Typo fix

    Co-Authored-By: Zach Marin <zacsimile@users.noreply.github.com>

commit d92e9cbcb7af9619ebb05eff345159dc67881368
Author: Kevin Dean <42547789+AdvancedImagingUTSW@users.noreply.github.com>
Date:   Fri Jul 8 13:16:35 2022 -0500

    Stage refactor and KCube Inertial Stage

    Co-Authored-By: Zach Marin <zacsimile@users.noreply.github.com>

commit 277a181029f1c5ed99d72595d8e3e6b16f4f00d1
Author: Kevin Dean <42547789+AdvancedImagingUTSW@users.noreply.github.com>
Date:   Fri Jul 8 11:58:43 2022 -0500

    Slight cleanup

    Co-Authored-By: Zach Marin <zacsimile@users.noreply.github.com>

commit 758447fcb6ab8f00a961fab6803c85512b1ddbea
Author: Kevin Dean <42547789+AdvancedImagingUTSW@users.noreply.github.com>
Date:   Fri Jul 8 11:54:56 2022 -0500

    Add API for high-res focusing piezo

    Co-Authored-By: Zach Marin <zacsimile@users.noreply.github.com>

commit dabe714a13380df91f52540f2eb24ce331885b5a
Author: Kevin Dean <42547789+AdvancedImagingUTSW@users.noreply.github.com>
Date:   Thu Jul 7 19:03:33 2022 -0500

    Offsets between channels

    Co-Authored-By: Zach Marin <zacsimile@users.noreply.github.com>

commit bbbc130525819b732d67d03225ab549b19a30c58
Author: Dax Collison <79557266+codeCollision4@users.noreply.github.com>
Date:   Thu Jul 7 18:46:12 2022 -0500

    Tiling Wizard #58

    Most things done need to calculate num of tiles. And discuss negative direction tiling

commit 8e3464efd2414e1ece3f61a7d5916dd34363760f
Author: Microscopy Innovation Lab <42547789+AdvancedImagingUTSW@users.noreply.github.com>
Date:   Thu Jul 7 16:09:36 2022 -0500

    Changes to size...

    For the future.  It is coming.  We shall add stuff to the right size.

commit 8bd21ea535b4195e2e149bb80dd04e85998e5c89
Author: Kevin Dean <42547789+AdvancedImagingUTSW@users.noreply.github.com>
Date:   Thu Jul 7 14:57:09 2022 -0500

    Progress bar tweaks

    Co-Authored-By: Zach Marin <zacsimile@users.noreply.github.com>

commit 04322a83a1f124f777d5222765f4d3376f93d9ff
Author: Kevin Dean <42547789+AdvancedImagingUTSW@users.noreply.github.com>
Date:   Thu Jul 7 14:52:18 2022 -0500

    Updated z-min

    Co-Authored-By: Zach Marin <zacsimile@users.noreply.github.com>

commit 0942bf63979452d87bf740c258956ad862f4aded
Author: Microscopy Innovation Lab <42547789+AdvancedImagingUTSW@users.noreply.github.com>
Date:   Thu Jul 7 14:43:23 2022 -0500

    Negligible oranization.

    Also added a first pass API for an ASI stage.

commit d9a52b040bb0b33f32a54527303f5791ba492c51
Author: Zach Marin <zacsimile@users.noreply.github.com>
Date:   Thu Jul 7 14:42:01 2022 -0500

    Lazy tiff loader for prototyping (#138)

    * Lazy tiff loader for prototyping

    * Forgotten imports

    * Space

    * Whoops

    * Whoops2

    * Convert to xyz slicing

    * Squeeze them

    * Comments

commit b09aee529dd6395471ec82f1dfabf1546521c469
Merge: b938d31 2c3701a
Author: Dean Lab @ UTSW <42547789+AdvancedImagingUTSW@users.noreply.github.com>
Date:   Thu Jul 7 13:14:48 2022 -0500

    Merge pull request #139 from AdvancedImagingUTSW/tiling_wizard

    Tiling Wizard

commit b938d31a3143b86a9f7b95b0bff943da51c0ae5e
Author: Microscopy Innovation Lab <42547789+AdvancedImagingUTSW@users.noreply.github.com>
Date:   Thu Jul 7 13:12:07 2022 -0500

    Progress Bar.

    #128 - Complete.  Can continue to add functionality to it as additional modes are added.

commit ad6f6e7ec55dbf797a4363fb2c095bdebc3886f2
Author: Kevin Dean <42547789+AdvancedImagingUTSW@users.noreply.github.com>
Date:   Thu Jul 7 11:32:57 2022 -0500

    Safer xz bounds

    Co-Authored-By: Zach Marin <zacsimile@users.noreply.github.com>

commit 36f2f78b41ca15ea72af50e8551201b1a08413cf
Author: Kevin Dean <42547789+AdvancedImagingUTSW@users.noreply.github.com>
Date:   Thu Jul 7 10:34:11 2022 -0500

    Turn off lasers when acquisition finishes

    Co-Authored-By: Zach Marin <zacsimile@users.noreply.github.com>

commit 0ce6dce9be84f017afc5ca87bfabdefc64807538
Author: Microscopy Innovation Lab <42547789+AdvancedImagingUTSW@users.noreply.github.com>
Date:   Thu Jul 7 05:59:31 2022 -0500

    Status bar

    #128 Status bar now semi-functional.  Top one runs continuously anytime we are acquiring data.  Bottom one is supposed to increment and report on our progress during a z-stack.  We can consider changing this to be a bit higher level.  Top one can go continuously in the continuous mode, for example, as an indeterminate progressbar.  In the z-stack mode, the top one could be come determinate, as the bottom one is now.  And then for time lapse, or multi position imaging, the bottom one could report on how long everything could take.  Total experiment duration.   Couldn't sleep, so knocked some of this out.  Now we just need to dial it in as we want it.

commit 75f3746e51e07d52e3c2a905fbf2a2445b9ffe77
Author: Kevin Dean <42547789+AdvancedImagingUTSW@users.noreply.github.com>
Date:   Wed Jul 6 18:02:55 2022 -0500

    Fix resolution offset

    Co-Authored-By: Zach Marin <zacsimile@users.noreply.github.com>

commit 75ab8f69b08d1cab1ac6e1fef667dc5bed45aee7
Author: Kevin Dean <42547789+AdvancedImagingUTSW@users.noreply.github.com>
Date:   Wed Jul 6 17:42:49 2022 -0500

    More stage refactoring

    Co-Authored-By: Zach Marin <zacsimile@users.noreply.github.com>

commit 19fa67e7f474624d6d52a4782402d0965b4191cb
Author: Kevin Dean <42547789+AdvancedImagingUTSW@users.noreply.github.com>
Date:   Wed Jul 6 17:14:57 2022 -0500

    Stage updates

    Co-Authored-By: Zach Marin <zacsimile@users.noreply.github.com>

* Tiling Wizard now populates Multiposition table

@zacsimile We need your help with iterating thru the table during a zstack in line 880 of aslm_model

* Undo weird behavior